import Head from "next/head";
import kanji from "../data/kanji-jouyou.json";
import { useState } from "react";
import NavBar from "../components/NavBar";
import RandomKanjiButton from "../components/RandomKanjiButton";
import Main from "../components/Main";
import getTodaysKanji from "../lib/GetTodaysKanji";

export default function Home() {
  const kanjiArr = Object.entries(kanji);
  const numKanji = kanjiArr.length;
  const getRandomKanjiIndex = () => Math.floor(Math.random() * numKanji);
  const [index, setIndex] = useState(getTodaysKanji(numKanji));

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Main>
        <p style={{ fontSize: "5rem" }}>{kanjiArr[index]["0"]}</p>
        <RandomKanjiButton onClick={() => setIndex(getRandomKanjiIndex())} />
      </Main>
    </div>
  );
}
