import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
import { generateRandomKanji } from "../lib/GenerateKanji.js";

export default function Quiz() {
  // Keep track of answers
  const numQuestions = 5;
  const [history, setHistory] = useState([]);
  const [isResultsShown, setIsResultsShown] = useState(false);

  // Get current kanji
  const curKanji = generateRandomKanji();

  // Setup question arr
  const answers = [curKanji];
  const numAnswers = 4;
  for (let i = 0; i < numAnswers; i++) {
    answers.push(generateRandomKanji());
  }

  const selectAnswer = (answer) => {
    setHistory([...history, { answer, curKanji }]);

    if (history.length + 1 >= numQuestions) {
      setIsResultsShown(true);
    } else {
      setIsResultsShown(false);
    }
  };

  const Questions = () => (
    <div>
      <h2>{curKanji.meanings[0]}</h2>
      <div>
        {answers.map((answer) => (
          <button
            key={answer.kanji}
            onClick={() => selectAnswer(answer)}
            style={{ fontSize: "2rem", margin: "5px", padding: "5px" }}
          >
            {answer.kanji}
          </button>
        ))}
      </div>
    </div>
  );

  const Results = () => (
    <>
      <button onClick={() => setHistory([])}>Reset?</button>
      <div>
        {history.map((entry) => (
          <div
            key={entry.answer.kanji}
            style={{ fontSize: "2rem", margin: "5px", padding: "5px" }}
          >
            <span>{entry.answer.kanji}</span> vs{" "}
            <span
              style={{
                color:
                  entry.answer.kanji == entry.curKanji.kanji ? "green" : "red",
              }}
            >
              {entry.curKanji.kanji}
            </span>
          </div>
        ))}
      </div>
    </>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Quiz</h1>
        <Link href={"/"}>Home</Link>

        {isResultsShown && history.length > 0 ? <Results /> : <Questions />}
      </main>
    </div>
  );
}
